# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Horse Life 98"
license = "LiLiQ-P-1.1"
licenselink = "https://github.com/juju2143/hugo-theme-horselife98/blob/master/LICENSE"
description = "Webcomic theme for Horse Life 98"
homepage = "https://yukiis.moe/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "J. P. Savard"
  homepage = "https://yukiis.moe/"
  